// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRS_vEqMw3HnJ9wu7BF5J_SEPowfXImWA',
    appId: '1:358026434934:web:7c832a86b056cc9cf14257',
    messagingSenderId: '358026434934',
    projectId: 'hostel-hunt-d3f9d',
    authDomain: 'hostel-hunt-d3f9d.firebaseapp.com',
    storageBucket: 'hostel-hunt-d3f9d.firebasestorage.app',
    measurementId: 'G-1STM5HPEJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv1YuNMHZiDfGWvGzl1ZlZKMSVX0JFY4E',
    appId: '1:358026434934:android:b8545842e67e9944f14257',
    messagingSenderId: '358026434934',
    projectId: 'hostel-hunt-d3f9d',
    storageBucket: 'hostel-hunt-d3f9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNGPWmILPUTQtrk2ioctFDFsb7diNHwuY',
    appId: '1:358026434934:ios:9fc989a5235c12a1f14257',
    messagingSenderId: '358026434934',
    projectId: 'hostel-hunt-d3f9d',
    storageBucket: 'hostel-hunt-d3f9d.firebasestorage.app',
    iosBundleId: 'com.example.hostelhuntApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNGPWmILPUTQtrk2ioctFDFsb7diNHwuY',
    appId: '1:358026434934:ios:9fc989a5235c12a1f14257',
    messagingSenderId: '358026434934',
    projectId: 'hostel-hunt-d3f9d',
    storageBucket: 'hostel-hunt-d3f9d.firebasestorage.app',
    iosBundleId: 'com.example.hostelhuntApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRS_vEqMw3HnJ9wu7BF5J_SEPowfXImWA',
    appId: '1:358026434934:web:9cde0b123550bc77f14257',
    messagingSenderId: '358026434934',
    projectId: 'hostel-hunt-d3f9d',
    authDomain: 'hostel-hunt-d3f9d.firebaseapp.com',
    storageBucket: 'hostel-hunt-d3f9d.firebasestorage.app',
    measurementId: 'G-Z47KS34K98',
  );
}
